
package org.example.wsdl.helloworldservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.example.xsd.sayhello.ObjectFactory;
import org.example.xsd.sayhello.SayHelloRequestType;
import org.example.xsd.sayhello.SayHelloResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldPortType", targetNamespace = "http://www.example.org/wsdl/HelloWorldService.wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.example.xsd.sayhello.SayHelloResponseType
     */
    @WebMethod
    @WebResult(name = "sayHelloResponseType", targetNamespace = "http://www.example.org/xsd/SayHello.xsd", partName = "parameters")
    public SayHelloResponseType sayHello(
        @WebParam(name = "sayHelloRequestType", targetNamespace = "http://www.example.org/xsd/SayHello.xsd", partName = "parameters")
        SayHelloRequestType parameters);

}
