
package org.example.wsdl.helloworldservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.example.xsd.sayhello.ObjectFactory;
import org.example.xsd.sayhello.SayHelloRequest;
import org.example.xsd.sayhello.SayHelloResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldPortType", targetNamespace = "http://helloworldservice.wsdl.example.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.example.xsd.sayhello.SayHelloResponse
     */
    @WebMethod
    @WebResult(name = "sayHelloResponse", targetNamespace = "http://sayhello.xsd.example.org/", partName = "parameters")
    public SayHelloResponse sayHello(
        @WebParam(name = "sayHelloRequest", targetNamespace = "http://sayhello.xsd.example.org/", partName = "parameters")
        SayHelloRequest parameters);

}
